package game;

public class Constants {
    public static final int DEFAULT_PORT = 8888;
    public static final int MAX_NUMBER_PLAYERS = 2;
    public static final int START_BALL_NEAR_PLAYER_ONE_X = 2;
    public static final int START_BALL_NEAR_PLAYER_ONE_Y = 4;
    public static final int START_BALL_NEAR_PLAYER_TWO_X = 7;
    public static final int START_BALL_NEAR_PLAYER_TWO_Y = 5;
    public static final int FIRST_VALUE_Y_START_ROCKET = 4;
    public static final int SECOND_VALUE_Y_START_ROCKET = 5;
    public static final int VALUE_X_START_ROCKET_PLAYER_ONE = 1;
    public static final int VALUE_X_START_ROCKET_PLAYER_TWO = 8;
    public static final int SPED_BALL_DEFAULT = 1;
    public static final int UPPER_BOUND_GAME_FIELD = 0;
    public static final int LOWER_BOUND_GAME_FIELD = 9;
    public static final int LEFT_BOUND_GAME_FIELD = 1;
    public static final int RIGHT_BOUND_GAME_FIELD = 8;
    public static final int LENGTH_GAME_FIELD = 10;
    public static final int WIDTH_GAME_FIELD = 10;
    public static final int INDEX_VALUE_POINT_PLAYER_ONE = 1;
    public static final int INDEX_VALUE_ROCKET_ONE_Y_PLAYER_ONE = 2;
    public static final int INDEX_VALUE_ROCKET_TWO_Y_PLAYER_ONE = 3;
    public static final int INDEX_VALUE_ROCKET_ONE_Y_PLAYER_TWO = 4;
    public static final int INDEX_VALUE_ROCKET_TWO_Y_PLAYER_TWO = 5;
    public static final int INDEX_VALUE_BALL_X = 6;
    public static final int INDEX_VALUE_BALL_Y = 7;
    public static final int INDEX_VALUE_POINT_PLAYER_TWO = 8;
    public static final int INDEX_FIRST_ROCKET = 0;
    public static final int INDEX_SECOND_ROCKET = 1;
    public static final String LEFT_COMMAND = "LEFT";
    public static final String RIGHT_COMMAND = "RIGHT";
    public static final String EXIT_COMMAND = "q";
    public static final String HOST = "localhost";
    public static final String SEPARATOR_STRING = ":";
    public static final char BALL_CHAR = 'o';
    public static final char EMPTY_CHAR = ' ';
    public static final char ROCKET_CHAR = '-';
    public static final char WALL_CHAR = '|';
    public static final char SEPARATOR_CHAR = ':';
}
